versions = {
    "version_11": {
        "id_prompt": 11,
        "prefix_prompt": "Simple, Classic, Minimal illustration, ((flat vector icon)) of",
        "suffix_prompt": "with flat color blocks, high contrast, beautiful, outline only, no details, solid color only.",
        "negative_prompt": "photorealistic, blurry, noisy, complex background, detailed texture, shadows, gradients",
        "version_description": "Minimal_flat_icon_no_details-512x512-kmean",
        "height": 512,
        "width": 512,
        "num_color": 12,
        "num_inference_steps": 25,
        "guidance_scale": 15,
        "use_image_compression": True,
        "num_attempts": 1,
        "verbose": True,
        "random_seed": 42,
    },
    "version_12": {
        "id_prompt": 11,
        "prefix_prompt": "Simple, Classic, Minimal illustration, ((flat vector icon)) of",
        "suffix_prompt": "with flat color blocks, high contrast, beautiful, outline only, no details, solid color only.",
        "negative_prompt": "photorealistic, blurry, noisy, complex background, detailed texture, shadows, gradients",
        "version_description": "Minimal_flat_icon_no_details-512x512-base",
        "height": 512,
        "width": 512,
        "num_color": 12,
        "num_inference_steps": 25,
        "guidance_scale": 15,
        "use_image_compression": False,
        "num_attempts": 1,
        "verbose": True,
        "random_seed": 42,
    },
    "version_13": {
        "id_prompt": 12,
        "prefix_prompt": "Simple, Classic, Minimal illustration, ((flat vector icon)) of",
        "suffix_prompt": "with flat color blocks, high contrast, beautiful, outline only, no details, solid color only.",
        "negative_prompt": "photorealistic, blurry, noisy, complex background, detailed texture, shadows, gradients",
        "version_description": "Minimal_flat_icon_no_details-768x768-kmean",
        "height": 768,
        "width": 768,
        "num_color": 12,
        "num_inference_steps": 25,
        "guidance_scale": 15,
        "use_image_compression": True,
        "num_attempts": 1,
        "verbose": True,
        "random_seed": 42,
    },
    "version_14": {
        "id_prompt": 12,
        "prefix_prompt": "Simple, Classic, Minimal illustration, ((flat vector icon)) of",
        "suffix_prompt": "with flat color blocks, high contrast, beautiful, outline only, no details, solid color only.",
        "negative_prompt": "photorealistic, blurry, noisy, complex background, detailed texture, shadows, gradients",
        "version_description": "Minimal_flat_icon_no_details-768x768-base",
        "height": 768,
        "width": 768,
        "num_color": 12,
        "num_inference_steps": 25,
        "guidance_scale": 15,
        "use_image_compression": False,
        "num_attempts": 1,
        "verbose": True,
        "random_seed": 42,
    },
    "version_15": {
        "id_prompt": 13,
        "prefix_prompt": "Simple, Classic, Minimal illustration, ((flat vector icon)) of",
        "suffix_prompt": "with flat color blocks, high contrast, beautiful, outline only, no details, solid color only.",
        "negative_prompt": "photorealistic, blurry, noisy, complex background, detailed texture, shadows, gradients",
        "version_description": "Minimal_flat_icon_no_details-1024x1024-kmean",
        "height": 1024,
        "width": 1024,
        "num_color": 12,
        "num_inference_steps": 25,
        "guidance_scale": 15,
        "use_image_compression": True,
        "num_attempts": 1,
        "verbose": True,
        "random_seed": 42,
    },
    "version_16": {
        "id_prompt": 13,
        "prefix_prompt": "Simple, Classic, Minimal illustration, ((flat vector icon)) of",
        "suffix_prompt": "with flat color blocks, high contrast, beautiful, outline only, no details, solid color only.",
        "negative_prompt": "photorealistic, blurry, noisy, complex background, detailed texture, shadows, gradients",
        "version_description": "Minimal_flat_icon_no_details-1024x1024-base",
        "height": 1024,
        "width": 1024,
        "num_color": 12,
        "num_inference_steps": 25,
        "guidance_scale": 15,
        "use_image_compression": False,
        "num_attempts": 1,
        "verbose": True,
        "random_seed": 42,
    },
        "version_17": {
        "id_prompt": 14,
        "prefix_prompt": "Simple, Classic of",
        "suffix_prompt": "with flat color blocks, high contrast, beautiful, outline only, no details, solid color only.",
        "negative_prompt": "photorealistic, blurry, noisy, complex background, detailed texture, shadows, gradients",
        "version_description": "Classic_no_details-1024x1024-base",
        "height": 1024,
        "width": 1024,
        "num_color": 12,
        "num_inference_steps": 25,
        "guidance_scale": 15,
        "use_image_compression": True,
        "num_attempts": 1,
        "verbose": True,
        "random_seed": 42,
    },
        "version_18": {
        "id_prompt": 15,
        "prefix_prompt": "Simple, Classic, Minimal illustration, ((flat vector icon)) of",
        "suffix_prompt": "with flat color blocks, high contrast, beautiful, outline only, no details, solid color only.",
        "negative_prompt": "photorealistic, blurry, noisy, complex background, detailed texture, shadows, gradients",
        "version_description": "Classic_no_details-384x385-base",
        "height": 384,
        "width": 384,
        "num_color": 12,
        "num_inference_steps": 25,
        "guidance_scale": 15,
        "use_image_compression": True,
        "num_attempts": 1,
        "verbose": True,
        "random_seed": 42,
    },

    "version_19": {
        "id_prompt": 16,
        "prefix_prompt": "",
        "suffix_prompt": "",
        "negative_prompt": "",
        "version_description": "no adjust prompt - 512x512",
        "height": 512,
        "width": 512,
        "num_color": 12,
        "num_inference_steps": 25,
        "guidance_scale": 15,
        "use_image_compression": True,
        "num_attempts": 1,
        "verbose": True,
        "random_seed": 42,
    },
        "version_20": {
        "id_prompt": 17,
        "prefix_prompt": "Simple, Classic, Minimal illustration, ((flat vector icon)) of",
        "suffix_prompt": "with flat color blocks, high contrast, beautiful, outline only, no details, solid color only.",
        "negative_prompt": "photorealistic, blurry, noisy, complex background, detailed texture, shadows, gradients",
        "version_description": "Minimal_flat_icon_no_details-768x768-kmean-weight_description",
        "height": 768,
        "width": 768,
        "num_color": 12,
        "num_inference_steps": 50,
        "guidance_scale": 15,
        "use_image_compression": True,
        "num_attempts": 1,
        "verbose": True,
        "random_seed": 42,
    },
}
